export const tab = 9;
export const ctrl = 17;
export const enter = 13;
export const alt = 18;
export const esc = 27;
export const space = 32;
export const arrowLeft = 37;
export const arrowUp = 38;
export const arrowRight = 39;
export const arrowDown = 40;
//# sourceMappingURL=keycodes.js.map